#!/bin/bash

function moduleExecute() {
	 [ ! -e "$DIR/containers" ] && \
                echo "No containers available yet. Create one with $0 container create <container-name>" && \
		return 0

	ls "$DIR/containers"
}

function commandInfo() {
    	echo "      list            List the currently available containers within the factory. "
	echo
	echo
}

